[package]
name = "state-replayer"
version = "0.0.1"
authors = ["Rakan Alhneiti <rakan.alhneiti@gmail.com>"]
description = "Raiden state replayer"
repository = "https://github.com/rakanalh/raiden-rust"
license = "MIT"
edition = "2021"
readme = "README.md"
keywords = ["blockchain", "ethereum", "layer-2", "scaling"]
rust-version = "1.59"

[[bin]]
name = "state-replayer"
path = "src/main.rs"

[dependencies]
# 3rd Party
colored = { version = "2.0.0" }
expanduser = { version = "1.2.1", default-features = false }
rusqlite = { version = "0.25.3", default-features = false }
structopt = { version = "0.3.25", default-features = false }

# Raiden
raiden-primitives = { path = "../../raiden/primitives" }
raiden-blockchain = { path = "../../raiden/blockchain" }
raiden-state-machine = { path = "../../raiden/state-machine", features = [ "storage" ] }
