[package]
name = "token-ops"
version = "0.0.1"
authors = ["Rakan Alhneiti <rakan.alhneiti@gmail.com>"]
description = "Raiden token operations"
repository = "https://github.com/rakanalh/raiden-rust"
license = "MIT"
edition = "2021"
readme = "README.md"
keywords = ["blockchain", "ethereum", "layer-2", "scaling"]
rust-version = "1.59"

[[bin]]
name = "token-ops"
path = "src/main.rs"

[dependencies]
# 3rd Party
ethsign = { version = "0.8.0" }
expanduser = { version = "1.2.1", default-features = false }
futures = { version = "0.3.21", default-features = false }
rpassword = { version = "5.0.1", default-features = false }
tracing = { version = "0.1.37", default-features = false }
tracing-subscriber = { version = "0.3.16", default-features = false }
structopt = { version = "0.3.25", default-features = false }
tokio = { version = "1.0", default-features = false, features = [ "macros" ] }
web3 = { version = "0.18.0", default-features = false, features = [ "http", "signing", "ws-tls-tokio" ] }

# Raiden
raiden-primitives = { path = "../../raiden/primitives" }
raiden-blockchain = { path = "../../raiden/blockchain" }
raiden-client = { path = "../../raiden/client" }
