pub const MIN_REVEAL_TIMEOUT: u32 = 1;
pub const DEFAULT_REVEAL_TIMEOUT: u32 = 50;
pub const DEFAULT_SETTLE_TIMEOUT: u32 = 500;
pub const DEFAULT_RETRY_TIMEOUT: f32 = 0.5;

pub const SNAPSHOT_STATE_CHANGE_COUNT: u16 = 500;
